owner: concordchat
repo: status

sites:
  - name: Proxy/Home
    url: https://concord.chat
  - name: API
    url: https://concord.chat/api/v5/auth/fingerprint

assignees:
  - VincentRPS

workflowSchedule:
  graphs: "6 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 1 * * *"
  summary: "15 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "30 3 * * *"
  uptime: "3 * * * *"

status-website:
  cname: status.concord.chat
  logoUrl: https://raw.githubusercontent.com/concordchat/branding/main/mascot.svg
  faviconSvg: https://raw.githubusercontent.com/concordchat/branding/main/mascot.svg
  theme: night
  name: Concord
  introTitle: "Ultra-fast, Scalable, Open-Source Chat Platform."
  introMessage: This is the status page for Concords Services.
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
